{
 "title": "Ollama Metrics Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests Per Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model) (ollama_requests_total)"
    }
   ]
  },
  {
   "title": "Count of responses by Token/s",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "ollama_tokens_per_second_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ollama_response_seconds_bucket[5m])) by (le, model))"
    }
   ]
  },
  {
   "title": "Tokens Generated Per Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model) (rate(ollama_tokens_generated_total[5m]))"
    }
   ]
  },
  {
   "title": "Evaluation Steps",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (model) (rate(ollama_eval_total[5m]))"
    }
   ]
  },
  {
   "title": "Model Load Time (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ollama_load_time_seconds_bucket[5m])) by (le, model))"
    }
   ]
  }
 ]
}